name: https://github.com/AnastasiaBrinati/demoMaven.git
on: [push]
jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/https://github.com/AnastasiaBrinati/demoMaven.git
      - name: build
        run: |
          cmake -S . -B build/linux -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          cmake --build build/linux
  build-on-windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/https://github.com/AnastasiaBrinati/demoMaven.git
      - name: build
        run: |
          cmake -S . -B build/windows -G "Visual Studio 16 2019" -Ax64 -Thost=x64
          cmake --build build/windows